services:
  - type: web
    name: app-crud
    env: php
    branch: main  # Git branch to deploy
    region: oregon  # Choose a region close to your users
    dockerfilePath: Dockerfile  # Path to your Dockerfile
    plan: free  # Free tier deployment

    # Port binding (make sure you expose port 80)
    ports:
      - "80:80"  # This binds port 80 on your machine to port 80 in the container

    envVars:
      - key: APP_KEY
        value: base64:uLxjQo4bZ48Rtl3uF6Qc6UtpJkWfIA2ni5aTT1RqtS8=  # Replace with actual app key
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: host.docker.internal  # Use this to connect to XAMPP MySQL from Docker
      - key: DB_PORT
        value: 3306  # Default MySQL port
      - key: DB_DATABASE
        value: app-crud
      - key: DB_USERNAME
        value: root  # Replace with your MySQL username if different
      - key: DB_PASSWORD
        value: <your-database-password>  # Replace with your actual DB password

    networks:
      - laravel-network

# Define the network
networks:
  laravel-network:
    driver: bridge
